# Define the Vagrant environment for Ansible 101
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Create the Goldstone Server
  config.vm.define :gldstn do |gldstn|
    gldstn.vm.box = "russmckendrick/centos7"
    gldstn.vm.hostname = "acs"
    gldstn.vm.network "private_network", ip: "192.168.56.98"
    gldstn.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    gldstn.vm.provision :shell, path: "bootstrap-gldstn.sh"
  end

end
