cp /etc/nova/nova.conf /etc/nova/nova.conf.orig
cp /etc/nova/api-paste.ini /etc/nova/api-paste.ini.orig
cp /etc/cinder/cinder.conf /etc/cinder/cinder.conf.orig
cp /etc/cinder/api-paste.ini /etc/cinder/api-paste.ini.orig
cp /etc/keystone/keystone.conf /etc/keystone/keystone.conf.orig
cp /etc/neutron/neutron.conf /etc/neutron/neutron.conf.orig
cp /etc/neutron/api-paste.ini /etc/neutron/api-paste.ini.orig
cp /etc/ceilometer/ceilometer.conf /etc/ceilometer/ceilometer.conf.orig
cp /etc/ceilometer/api_paste.ini /etc/ceilometer/api_paste.ini.orig
cp /etc/glance/glance-cache.conf /etc/glance/glance-cache.conf.orig
cp /etc/glance/glance-api.conf /etc/glance/glance-api.conf.orig
cp /etc/glance/glance-registry.conf /etc/glance/glance-registry.conf.orig
cp /etc/glance/glance-scrubber.conf /etc/glance/glance-scrubber.conf.orig
